// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/account/account.proto

package account

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_GetAccount_FullMethodName           = "/account.AccountService/GetAccount"
	AccountService_GetBalance_FullMethodName           = "/account.AccountService/GetBalance"
	AccountService_UpdateBalance_FullMethodName        = "/account.AccountService/UpdateBalance"
	AccountService_CreateHold_FullMethodName           = "/account.AccountService/CreateHold"
	AccountService_ReleaseHold_FullMethodName          = "/account.AccountService/ReleaseHold"
	AccountService_StreamBalanceUpdates_FullMethodName = "/account.AccountService/StreamBalanceUpdates"
	AccountService_BatchUpdateBalances_FullMethodName  = "/account.AccountService/BatchUpdateBalances"
	AccountService_MonitorAccounts_FullMethodName      = "/account.AccountService/MonitorAccounts"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Account Service Definition
type AccountServiceClient interface {
	// Unary RPCs
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error)
	CreateHold(ctx context.Context, in *CreateHoldRequest, opts ...grpc.CallOption) (*CreateHoldResponse, error)
	ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*ReleaseHoldResponse, error)
	// Server streaming RPC
	StreamBalanceUpdates(ctx context.Context, in *StreamBalanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BalanceUpdate], error)
	// Client streaming RPC
	BatchUpdateBalances(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateBalanceRequest, BatchUpdateResponse], error)
	// Bidirectional streaming RPC
	MonitorAccounts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MonitorRequest, AccountEvent], error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, AccountService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBalanceResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateHold(ctx context.Context, in *CreateHoldRequest, opts ...grpc.CallOption) (*CreateHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHoldResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*ReleaseHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseHoldResponse)
	err := c.cc.Invoke(ctx, AccountService_ReleaseHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) StreamBalanceUpdates(ctx context.Context, in *StreamBalanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BalanceUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountService_ServiceDesc.Streams[0], AccountService_StreamBalanceUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBalanceRequest, BalanceUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamBalanceUpdatesClient = grpc.ServerStreamingClient[BalanceUpdate]

func (c *accountServiceClient) BatchUpdateBalances(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateBalanceRequest, BatchUpdateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountService_ServiceDesc.Streams[1], AccountService_BatchUpdateBalances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateBalanceRequest, BatchUpdateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_BatchUpdateBalancesClient = grpc.ClientStreamingClient[UpdateBalanceRequest, BatchUpdateResponse]

func (c *accountServiceClient) MonitorAccounts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MonitorRequest, AccountEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountService_ServiceDesc.Streams[2], AccountService_MonitorAccounts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MonitorRequest, AccountEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_MonitorAccountsClient = grpc.BidiStreamingClient[MonitorRequest, AccountEvent]

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// Account Service Definition
type AccountServiceServer interface {
	// Unary RPCs
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error)
	CreateHold(context.Context, *CreateHoldRequest) (*CreateHoldResponse, error)
	ReleaseHold(context.Context, *ReleaseHoldRequest) (*ReleaseHoldResponse, error)
	// Server streaming RPC
	StreamBalanceUpdates(*StreamBalanceRequest, grpc.ServerStreamingServer[BalanceUpdate]) error
	// Client streaming RPC
	BatchUpdateBalances(grpc.ClientStreamingServer[UpdateBalanceRequest, BatchUpdateResponse]) error
	// Bidirectional streaming RPC
	MonitorAccounts(grpc.BidiStreamingServer[MonitorRequest, AccountEvent]) error
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAccountServiceServer) UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBalance not implemented")
}
func (UnimplementedAccountServiceServer) CreateHold(context.Context, *CreateHoldRequest) (*CreateHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHold not implemented")
}
func (UnimplementedAccountServiceServer) ReleaseHold(context.Context, *ReleaseHoldRequest) (*ReleaseHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseHold not implemented")
}
func (UnimplementedAccountServiceServer) StreamBalanceUpdates(*StreamBalanceRequest, grpc.ServerStreamingServer[BalanceUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamBalanceUpdates not implemented")
}
func (UnimplementedAccountServiceServer) BatchUpdateBalances(grpc.ClientStreamingServer[UpdateBalanceRequest, BatchUpdateResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchUpdateBalances not implemented")
}
func (UnimplementedAccountServiceServer) MonitorAccounts(grpc.BidiStreamingServer[MonitorRequest, AccountEvent]) error {
	return status.Error(codes.Unimplemented, "method MonitorAccounts not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateHold(ctx, req.(*CreateHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReleaseHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReleaseHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ReleaseHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReleaseHold(ctx, req.(*ReleaseHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_StreamBalanceUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBalanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).StreamBalanceUpdates(m, &grpc.GenericServerStream[StreamBalanceRequest, BalanceUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamBalanceUpdatesServer = grpc.ServerStreamingServer[BalanceUpdate]

func _AccountService_BatchUpdateBalances_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountServiceServer).BatchUpdateBalances(&grpc.GenericServerStream[UpdateBalanceRequest, BatchUpdateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_BatchUpdateBalancesServer = grpc.ClientStreamingServer[UpdateBalanceRequest, BatchUpdateResponse]

func _AccountService_MonitorAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountServiceServer).MonitorAccounts(&grpc.GenericServerStream[MonitorRequest, AccountEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_MonitorAccountsServer = grpc.BidiStreamingServer[MonitorRequest, AccountEvent]

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _AccountService_GetBalance_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _AccountService_UpdateBalance_Handler,
		},
		{
			MethodName: "CreateHold",
			Handler:    _AccountService_CreateHold_Handler,
		},
		{
			MethodName: "ReleaseHold",
			Handler:    _AccountService_ReleaseHold_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBalanceUpdates",
			Handler:       _AccountService_StreamBalanceUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BatchUpdateBalances",
			Handler:       _AccountService_BatchUpdateBalances_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MonitorAccounts",
			Handler:       _AccountService_MonitorAccounts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/account/account.proto",
}
