// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: account/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CustomerId       string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountType      string                 `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance          float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,7,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	InterestRate     float64                `protobuf:"fixed64,9,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	OpenedAt         int64                  `protobuf:"varint,10,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *Account) GetOpenedAt() int64 {
	if x != nil {
		return x.OpenedAt
	}
	return 0
}

func (x *Account) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Account) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Balance          float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Error            *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *GetBalanceResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionRef string                 `protobuf:"bytes,3,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBalanceRequest) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

func (x *UpdateBalanceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    float64                `protobuf:"fixed64,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceResponse) Reset() {
	*x = UpdateBalanceResponse{}
	mi := &file_account_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceResponse) ProtoMessage() {}

func (x *UpdateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBalanceResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *UpdateBalanceResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateHoldRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TransactionRef string                 `protobuf:"bytes,4,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateHoldRequest) Reset() {
	*x = CreateHoldRequest{}
	mi := &file_account_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldRequest) ProtoMessage() {}

func (x *CreateHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldRequest.ProtoReflect.Descriptor instead.
func (*CreateHoldRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHoldRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateHoldRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateHoldRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateHoldRequest) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

type CreateHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHoldResponse) Reset() {
	*x = CreateHoldResponse{}
	mi := &file_account_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldResponse) ProtoMessage() {}

func (x *CreateHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldResponse.ProtoReflect.Descriptor instead.
func (*CreateHoldResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{8}
}

func (x *CreateHoldResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *CreateHoldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateHoldResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReleaseHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHoldRequest) Reset() {
	*x = ReleaseHoldRequest{}
	mi := &file_account_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHoldRequest) ProtoMessage() {}

func (x *ReleaseHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHoldRequest.ProtoReflect.Descriptor instead.
func (*ReleaseHoldRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseHoldRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ReleaseHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHoldResponse) Reset() {
	*x = ReleaseHoldResponse{}
	mi := &file_account_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHoldResponse) ProtoMessage() {}

func (x *ReleaseHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHoldResponse.ProtoReflect.Descriptor instead.
func (*ReleaseHoldResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseHoldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseHoldResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type StreamBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBalanceRequest) Reset() {
	*x = StreamBalanceRequest{}
	mi := &file_account_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBalanceRequest) ProtoMessage() {}

func (x *StreamBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBalanceRequest.ProtoReflect.Descriptor instead.
func (*StreamBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{11}
}

func (x *StreamBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type BalanceUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance          float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceUpdate) Reset() {
	*x = BalanceUpdate{}
	mi := &file_account_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdate) ProtoMessage() {}

func (x *BalanceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdate.ProtoReflect.Descriptor instead.
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{12}
}

func (x *BalanceUpdate) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceUpdate) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceUpdate) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *BalanceUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BatchUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Errors        []*Error               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateResponse) Reset() {
	*x = BatchUpdateResponse{}
	mi := &file_account_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateResponse) ProtoMessage() {}

func (x *BatchUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateResponse) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{13}
}

func (x *BatchUpdateResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchUpdateResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchUpdateResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	mi := &file_account_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{14}
}

func (x *MonitorRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MonitorRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type AccountEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountEvent) Reset() {
	*x = AccountEvent{}
	mi := &file_account_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEvent) ProtoMessage() {}

func (x *AccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEvent.ProtoReflect.Descriptor instead.
func (*AccountEvent) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{15}
}

func (x *AccountEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AccountEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AccountEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_account_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_account_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_account_account_proto_rawDescGZIP(), []int{16}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_account_account_proto protoreflect.FileDescriptor

const file_account_account_proto_rawDesc = "" +
	"\n" +
	"\x15account/account.proto\x12\aaccount\"\xff\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\faccount_type\x18\x04 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\a \x01(\x01R\x10availableBalance\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rinterest_rate\x18\t \x01(\x01R\finterestRate\x12\x1b\n" +
	"\topened_at\x18\n" +
	" \x01(\x03R\bopenedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"f\n" +
	"\x12GetAccountResponse\x12*\n" +
	"\aaccount\x18\x01 \x01(\v2\x10.account.AccountR\aaccount\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\x0e.account.ErrorR\x05error\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x81\x01\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\x01R\x10availableBalance\x12$\n" +
	"\x05error\x18\x03 \x01(\v2\x0e.account.ErrorR\x05error\"\x98\x01\n" +
	"\x14UpdateBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12'\n" +
	"\x0ftransaction_ref\x18\x03 \x01(\tR\x0etransactionRef\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"x\n" +
	"\x15UpdateBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x01R\n" +
	"newBalance\x12$\n" +
	"\x05error\x18\x03 \x01(\v2\x0e.account.ErrorR\x05error\"\x8b\x01\n" +
	"\x11CreateHoldRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0ftransaction_ref\x18\x04 \x01(\tR\x0etransactionRef\"m\n" +
	"\x12CreateHoldResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12$\n" +
	"\x05error\x18\x03 \x01(\v2\x0e.account.ErrorR\x05error\"-\n" +
	"\x12ReleaseHoldRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"U\n" +
	"\x13ReleaseHoldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\x0e.account.ErrorR\x05error\"5\n" +
	"\x14StreamBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x93\x01\n" +
	"\rBalanceUpdate\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\x01R\x10availableBalance\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x85\x01\n" +
	"\x13BatchUpdateResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12&\n" +
	"\x06errors\x18\x03 \x03(\v2\x0e.account.ErrorR\x06errors\"P\n" +
	"\x0eMonitorRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\"~\n" +
	"\fAccountEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x04\n" +
	"\x0eAccountService\x12E\n" +
	"\n" +
	"GetAccount\x12\x1a.account.GetAccountRequest\x1a\x1b.account.GetAccountResponse\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.account.GetBalanceRequest\x1a\x1b.account.GetBalanceResponse\x12N\n" +
	"\rUpdateBalance\x12\x1d.account.UpdateBalanceRequest\x1a\x1e.account.UpdateBalanceResponse\x12E\n" +
	"\n" +
	"CreateHold\x12\x1a.account.CreateHoldRequest\x1a\x1b.account.CreateHoldResponse\x12H\n" +
	"\vReleaseHold\x12\x1b.account.ReleaseHoldRequest\x1a\x1c.account.ReleaseHoldResponse\x12O\n" +
	"\x14StreamBalanceUpdates\x12\x1d.account.StreamBalanceRequest\x1a\x16.account.BalanceUpdate0\x01\x12T\n" +
	"\x13BatchUpdateBalances\x12\x1d.account.UpdateBalanceRequest\x1a\x1c.account.BatchUpdateResponse(\x01\x12E\n" +
	"\x0fMonitorAccounts\x12\x17.account.MonitorRequest\x1a\x15.account.AccountEvent(\x010\x01B>Z<github.com/Caesarsage/bankflow/account-service/proto/accountb\x06proto3"

var (
	file_account_account_proto_rawDescOnce sync.Once
	file_account_account_proto_rawDescData []byte
)

func file_account_account_proto_rawDescGZIP() []byte {
	file_account_account_proto_rawDescOnce.Do(func() {
		file_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)))
	})
	return file_account_account_proto_rawDescData
}

var file_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_account_account_proto_goTypes = []any{
	(*Account)(nil),               // 0: account.Account
	(*GetAccountRequest)(nil),     // 1: account.GetAccountRequest
	(*GetAccountResponse)(nil),    // 2: account.GetAccountResponse
	(*GetBalanceRequest)(nil),     // 3: account.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 4: account.GetBalanceResponse
	(*UpdateBalanceRequest)(nil),  // 5: account.UpdateBalanceRequest
	(*UpdateBalanceResponse)(nil), // 6: account.UpdateBalanceResponse
	(*CreateHoldRequest)(nil),     // 7: account.CreateHoldRequest
	(*CreateHoldResponse)(nil),    // 8: account.CreateHoldResponse
	(*ReleaseHoldRequest)(nil),    // 9: account.ReleaseHoldRequest
	(*ReleaseHoldResponse)(nil),   // 10: account.ReleaseHoldResponse
	(*StreamBalanceRequest)(nil),  // 11: account.StreamBalanceRequest
	(*BalanceUpdate)(nil),         // 12: account.BalanceUpdate
	(*BatchUpdateResponse)(nil),   // 13: account.BatchUpdateResponse
	(*MonitorRequest)(nil),        // 14: account.MonitorRequest
	(*AccountEvent)(nil),          // 15: account.AccountEvent
	(*Error)(nil),                 // 16: account.Error
}
var file_account_account_proto_depIdxs = []int32{
	0,  // 0: account.GetAccountResponse.account:type_name -> account.Account
	16, // 1: account.GetAccountResponse.error:type_name -> account.Error
	16, // 2: account.GetBalanceResponse.error:type_name -> account.Error
	16, // 3: account.UpdateBalanceResponse.error:type_name -> account.Error
	16, // 4: account.CreateHoldResponse.error:type_name -> account.Error
	16, // 5: account.ReleaseHoldResponse.error:type_name -> account.Error
	16, // 6: account.BatchUpdateResponse.errors:type_name -> account.Error
	1,  // 7: account.AccountService.GetAccount:input_type -> account.GetAccountRequest
	3,  // 8: account.AccountService.GetBalance:input_type -> account.GetBalanceRequest
	5,  // 9: account.AccountService.UpdateBalance:input_type -> account.UpdateBalanceRequest
	7,  // 10: account.AccountService.CreateHold:input_type -> account.CreateHoldRequest
	9,  // 11: account.AccountService.ReleaseHold:input_type -> account.ReleaseHoldRequest
	11, // 12: account.AccountService.StreamBalanceUpdates:input_type -> account.StreamBalanceRequest
	5,  // 13: account.AccountService.BatchUpdateBalances:input_type -> account.UpdateBalanceRequest
	14, // 14: account.AccountService.MonitorAccounts:input_type -> account.MonitorRequest
	2,  // 15: account.AccountService.GetAccount:output_type -> account.GetAccountResponse
	4,  // 16: account.AccountService.GetBalance:output_type -> account.GetBalanceResponse
	6,  // 17: account.AccountService.UpdateBalance:output_type -> account.UpdateBalanceResponse
	8,  // 18: account.AccountService.CreateHold:output_type -> account.CreateHoldResponse
	10, // 19: account.AccountService.ReleaseHold:output_type -> account.ReleaseHoldResponse
	12, // 20: account.AccountService.StreamBalanceUpdates:output_type -> account.BalanceUpdate
	13, // 21: account.AccountService.BatchUpdateBalances:output_type -> account.BatchUpdateResponse
	15, // 22: account.AccountService.MonitorAccounts:output_type -> account.AccountEvent
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_account_account_proto_init() }
func file_account_account_proto_init() {
	if File_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_account_proto_rawDesc), len(file_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_account_proto_goTypes,
		DependencyIndexes: file_account_account_proto_depIdxs,
		MessageInfos:      file_account_account_proto_msgTypes,
	}.Build()
	File_account_account_proto = out.File
	file_account_account_proto_goTypes = nil
	file_account_account_proto_depIdxs = nil
}
